volumes:
  postgres:
  nextcloud:

networks:
  nextcloud_network:

services:
  postgres:
    image: postgres:13
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextclouduser
      POSTGRES_PASSWORD: DEdfGGRwwefrCVb
    networks:
      - nextcloud_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 4
      start_period: 60s

  redis:
    image: redis:7.2.0
    command: ["redis-server", "--requirepass", "D111111d"] 
    ports: 
      - 6379:6379
    networks:
      - nextcloud_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s

  nextcloud:
    image: nextcloud:25.0.10
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextclouduser
      POSTGRES_PASSWORD: DEdfGGRwwefrCVb
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: D111111d
    networks:
      - nextcloud_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    