volumes:
  wordpress:
  mariadb:

networks:
  wordpress_network:

services:
  wordpress: 
    image: bitnami/wordpress:6.3.1-debian-11-r7
    environment:
      WORDPRESS_DATABASE_HOST: mariadb
      WORDPRESS_DATABASE_USER: mariadbuser1
      WORDPRESS_DATABASE_PASSWORD: jrk5akXml4MSe3
      WORDPRESS_DATABASE_NAME: wordpressdb
      WORDPRESS_USERNAME: user
      WORDPRESS_PASSWORD: bitnami
      WORDPRESS_EMAIL: test@gmail.com
      WORDPRESS_FIRST_NAME: FirstName
      WORDPRESS_LAST_NAME: LastName
      WORDPRESS_BLOG_NAME: User's blog
      WORDPRESS_SMTP_HOST: smtp.gmail.com
      WORDPRESS_SMTP_PORT: 587
      WORDPRESS_SMTP_USER: test@gmail.com
      WORDPRESS_SMTP_PASSWORD: D111!!!d
    volumes:
      - wordpress:/bitnami/wordpress
    ports:
      - 8080:8080
    networks:
      - wordpress_network
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/8080' || exit 1
      interval: 10s
      timeout: 5s
      retries: 4
      start_period: 20s
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    image: mariadb:11.1
    networks:
      - wordpress_network
    volumes:
      - mariadb:/var/lib/mysql
    environment:
        MARIADB_DATABASE: wordpressdb
        MARIADB_ROOT_PASSWORD: z2Z4JJpVWARS
        MARIADB_USER: mariadbuser1
        MARIADB_PASSWORD: jrk5akXml4MSe3
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"] # For MariaDB there is a special check defined on ther website. It is a script written inside of their official images named healthcheck.sh
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s